### ISSUE TITLE
2 more pieces missing from centre drum

### ISSUE THREAD

**Issue by psjshep** [ekaggrat/eptaora#3]
Thx for including the pinion pin stl....

There are 2 other pieces missing from the end of the centre drum... in diagram https://cdn.hackaday.io/images/6511831665221138021.jpg 

The disk & the gear on the far left hand side, both labelled with the letter "A"

Phil

**Comment by ekaggrat** [comment]
those are optional to connect the next module. I will release them later

**Comment by psjshep** [comment]
ok... thx
