### ISSUE TITLE
Wire diameters

### ISSUE THREAD

**Issue by carr-james** [ekaggrat/eptaora#4]
Really appreciate this open source project you've put together, it looks very cool and I'd love to build one myself! I am confused by the instructions as there are some places where it mentions 0.2mm diameter spring wire and some places that call for 0.4mm, which is it?

**Comment by ekaggrat** [comment]
it is 0.4 for the hooks and 0.2-0.3 foe the springs .a little variation wont matter.

**Comment by carr-james** [comment]
Ah brilliant, I ordered both just in case. Glad to know they will both be used! Maybe a bill of materials would be useful for others, as it can be difficult to figure out what's needed
