### ISSUE TITLE
Same clock on Kickstarter?

### ISSUE THREAD

**Issue by fowie** [ekaggrat/eptaora#6]
I just got an ad for this: https://www.kickstarter.com/projects/rantoge-clock/rantogean-electromechanical-cam-clock-that-hears-the-time?utm_medium=referral&utm_source=40.backer.camp&ref=a6h4o5&fbclid=PAAab_XvsK3_xboIc1ZgPgLhKaUrbI-6-pxA3x6pTBT-lGT7wQqS_qC0Qww5c
Hopefully it's because you sold them the rights, not because they just copied this GIT repo.

**Comment by ekaggrat** [comment]
thanks for your concern. Even i am seeing it as a n ad for a long time. But unfortunately it has been copied without any consent. It is the way things are today and publishing online has always the risk of being copied .
