### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by 1JonaB1** [ekaggrat/eptaora#8]
Hello, your project seems great.
I would like to modify the clock to work with different motors and machine some parts for the Clock out of aluminum. For this the CAD files would be extremely helpful

Jona

**Comment by jschoch** [comment]
https://fablabsendai-flat.com/2019/11/04/mechanical7seg_en/

**Comment by ekaggrat** [comment]
yes it is not original and is inspired from that project. so you can very well make your own derivative. I never claimed to invent it . I jus optimized it to be smaller and 3d printable
